version: 2
jobs:
  build:
    docker:
      - image: quay.io/3scale/s2i:v1.1.5-ce
    environment:
      REGISTRY: "${DOCKER_REGISTRY}/3scale"
    working_directory: /root/apicast-cloud
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run: cd apicast && make build test
      - deploy:
          name: Push docker image
          command: |
            if [ -n "${CIRCLE_TAG}" ] || [ -n "${CIRCLE_BRANCH}" ]; then
              docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}" "${DOCKER_REGISTRY}"
              cd apicast && make push REMOTE_IMAGE_NAME=apicast-sandbox:apicast-${CIRCLE_TAG:-${CIRCLE_BRANCH}}
            fi

