version: 2
jobs:
  build:
    docker:
      - image: quay.io/3scale/s2i:v1.1.5-ce
    environment:
      REGISTRY: "${DOCKER_REGISTRY}/3scale"
    working_directory: /root/apicast-cloud
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run: cd apicast && make build test
      - run: cd mapping-service && make build IMAGE_TAG=${CIRCLE_TAG:-${CIRCLE_BRANCH}}
      - deploy:
          name: Push docker image
          command: |
            if [ -n "${CIRCLE_TAG}" ] || [ -n "${CIRCLE_BRANCH}" ]; then
              docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}" "${DOCKER_REGISTRY}"
              (cd apicast && make push REMOTE_IMAGE_NAME=apicast-cloud-hosted:apicast-${CIRCLE_TAG:-${CIRCLE_BRANCH}})
              (cd mapping-service && make push IMAGE_TAG=${CIRCLE_TAG:-${CIRCLE_BRANCH}})
            fi

# TODO: remove this once CircleCI 2.0 supports building from tags
# https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/5
deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"
