version: 2
jobs:
  deploy:
    docker:
      - image: quay.io/3scale/s2i:v1.1.8-ce
        environment:
          APICAST_VERSION: master
    environment:
      DOCKER_REGISTRY: "quay.io"
    working_directory: /root/apicast-cloud
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run: cd apicast && make builder test
      - run: cd apicast && make build test
      - run: cd mapping-service && make build IMAGE_TAG=${CIRCLE_TAG:-${CIRCLE_BRANCH}}
      - deploy:
          name: Push docker image
          command: |
            if [ -n "${CIRCLE_TAG}" ] || [ -n "${CIRCLE_BRANCH}" ]; then
              docker login -u="${DOCKER_USERNAME}" --password-stdin "${DOCKER_REGISTRY}" <<< "${DOCKER_PASSWORD}"
              (cd apicast && make push REMOTE_IMAGE_NAME=apicast-cloud-hosted:apicast-${CIRCLE_TAG:-${CIRCLE_BRANCH}})
              (cd mapping-service && make push IMAGE_TAG=${CIRCLE_TAG:-${CIRCLE_BRANCH}})
            fi

  apicast-test:
    docker:
      - image: quay.io/3scale/s2i-openresty-centos7:1.13.6.1-rover6
        environment:
          TEST_NGINX_BINARY: openresty
          LUA_BIN_PATH: /opt/app-root/bin
    working_directory: /opt/app-root/apicast-cloud-hosted
    steps:
      - checkout
      - restore_cache:
          keys:
            - apicast-cloud-hosted-rover-{{ arch }}-{{ checksum "apicast/Roverfile.lock" }}
            - apicast-cloud-hosted-rover-{{ arch }}-{{ .Branch }}
            - apicast-cloud-hosted-rover-{{ arch }}-master
      - run: cd apicast && rover install
      - save_cache:
          key: apicast-cloud-hosted-rover-{{ arch }}-{{ checksum "apicast/Roverfile.lock" }}
          paths:
            - apicast/lua_modules
      - restore_cache:
          keys:
            - apicast-cloud-hosted-cpanm-{{ arch }}-{{ checksum "apicast/cpanfile" }}
            - apicast-cloud-hosted-cpanm-{{ arch }}-{{ .Branch }}
            - apicast-cloud-hosted-{{ arch }}-master
      - run: /usr/libexec/s2i/entrypoint cpanm --notest --installdeps ./apicast
      - save_cache:
          key: apicast-cloud-hosted-cpanm-{{ arch }}-{{ checksum "apicast/cpanfile" }}
          paths:
            - ~/perl5
      - run: mkdir -p apicast/tmp/junit
      - run:
          command: cd apicast && /usr/libexec/s2i/entrypoint sh -c 'rover exec prove --harness=TAP::Harness::JUnit $(circleci tests glob "t/**/*.t" |  circleci tests split --split-by=timings --timings-type=filename)'
          environment:
            JUNIT_OUTPUT_FILE: tmp/junit/prove.xml
            TEST_NGINX_ERROR_LOG: tmp/prove.log
      - store_artifacts:
          path: apicast/tmp
          destination: tmp
      - store_test_results:
          path: apicast/tmp/junit
workflows:
  version: 2
  build_and_test:
    jobs:
      - apicast-test
      - deploy:
          context: org-global
          requires:
            - apicast-test

# TODO: remove this once CircleCI 2.0 supports building from tags
# https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/5
deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"
