apiVersion: v1
kind: ImageStream
metadata:
  name: apicast
  labels:
    app: apicast
spec:
  tags:
  - name: master-builder
    from:
      kind: DockerImage
      name: quay.io/3scale/apicast:master-builder
    importPolicy:
      scheduled: true
