apiVersion: v1
kind: Template
metadata:
  name: "apicast-cloud-hosted"
objects:

- apiVersion: v1
  kind: Route
  metadata:
    name: apicast-router
    labels:
      app: apicast-router
  spec:
    host: apicast.${ENVIRONMENT}.gw.apicast.io
    to:
      kind: Service
      name: apicast
    port:
      targetPort: proxy
    wildcardPolicy: Subdomain
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Allow

- apiVersion: v1
  kind: Route
  metadata:
    name: apicast-${ENVIRONMENT}-policies
  spec:
    host: apicast.${ENVIRONMENT}.${WILDCARD_DOMAIN}
    path: /policies
    to:
      kind: Service
      name: apicast
    port:
      targetPort: management
    wildcardPolicy: None
    tls:
      termination: edge

parameters:

- description: "Deployment environment. `staging` or `production`"
  name: ENVIRONMENT
  required: true

- description: "Openshift Cluster Wildcard Domain"
  name: WILDCARD_DOMAIN
  required: true
