name: test

on:
  pull_request:
    branches:
      - master
  push:
    # only trigger on branches, not on tags
    branches: ["**"]

jobs:
  apicast-test:
    runs-on: ubuntu-latest
    env:
      BUILD_INFO: local
    steps:
      - uses: actions/checkout@v2

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: cd apicast && make build

      - name: Test
        run: cd apicast && make test && make prove

  mapping-service-test:
    runs-on: ubuntu-latest
    env:
      BUILD_INFO: local
    steps:
      - uses: actions/checkout@v2

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: cd mapping-service && make build

      - name: Test
        run: cd mapping-service &&  make busted && make test && make prove
